name: reusable-build

on: 
    workflow_call:
        inputs:
            app_name:
                description: This is the app name for inputs
                type: string
                required: true

            environment:
                description: This is the environment for inputs section
                type: string
                required: true
                default: 'staging'
        secrets:
            docker_token:
                description: This is the docker token inside the secrets section
                required: true

jobs:
    take_input:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Take input from the inputs section
              run: echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

            - name: Verify the docker token 
              run: |
                  if [ -n "${{ secrets.docker_token }}" ]; then
                      echo "Docker token is set: true"
                  else
                      echo "Docker token is set: false"
                      exit 1
                  fi
