name: secrets-workflow

on:
    push:

jobs:
    secret:
        runs-on: ubuntu-latest
        steps:
            - name: Print the msg that the secret has been read
              env:
                  SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
              run: |
                  if [ -n "$SECRET" ]; then
                      echo "The secret is set: true"
                  else
                      echo "Failed to read the secret!"
                  fi
                  
            - name: Directly Print The Secret
              run: echo "Print the msg ${{ secrets.MY_SECRET_MESSAGE }}"
